apiVersion: v1
kind: Namespace
metadata:
  name: production-web
  labels:
    environment: production
    app.kubernetes.io/managed-by: butler-solutions
    app.kubernetes.io/part-of: butler-web-platform
