apiVersion: v1
kind: Service
metadata:
  name: butler-solutions-web
  namespace: production-web
  labels:
    app: butler-solutions-web
    app.kubernetes.io/name: butler-solutions-web
    app.kubernetes.io/part-of: butler-web-platform
spec:
  selector:
    app: butler-solutions-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
